### ISSUE TITLE
Issue with output format

### ISSUE THREAD

**Issue by overthink** [hamadmarri/SortableChallenge#1]
Hi Hamad,

I was trying to evaluate your solution but there is a problem with the output format.  I need the listings that are output to be exactly the same as the listings in listings.txt.  It looks like your solution strips some punctuation out of the listings.  e.g.

yours:

`Kodak EasyShare Touch M577 Digitalkamera (14 Megapixel  5-fach opt. Zoom  7 6 cm (3 Zoll) Display) schwarz`

expected:

`Kodak EasyShare Touch M577 Digitalkamera (14 Megapixel, 5-fach opt. Zoom, 7,6 cm (3 Zoll) Display) schwarz`

(Commas are missing in yours.)

If you are able to fix this up I'd be happy to take another look at your submission.

Thanks!

Mark (from sortable.com)

**Comment by hamadmarri** [comment]
Hello Mark, 
Thanks for letting me know about this issue. It is fixed now please give it one more try: -
wget https://github.com/hamadmarri/SortableChallenge/releases/download/v1.1/sortableChallenge.zip
unzip sortableChallenge.zip
chmod +x ./run.sh
./run.sh

Find the source code in this page https://github.com/hamadmarri/SortableChallenge/releases/tag/v1.1

Thanks
Hamad

**Comment by overthink** [comment]
Thanks Hamad.  Can you verify that the expected size of your output file is 48544 bytes?

**Comment by hamadmarri** [comment]
Yes it is 48544 bytes.

-rw-rw-r-- 1 hamad hamad  48544 Feb 10 01:05 results.txt
